### ISSUE TITLE
Chart releaser is failing

### ISSUE THREAD

**Issue by simenandre** [caddyserver/ingress#117]
Hello 👋

Thank you for this excellent project!

I am an eager user of the Caddy Ingress Controller and want to help. There seems to be something [wrong with the chart release workflow](https://github.com/caddyserver/ingress/actions/runs/3628872977/jobs/6120410427).

Is there anything I can do to help?

**Comment by cobraz** [comment]
It seems like this is caused by [`version` tag in `Chart.yaml`](https://github.com/caddyserver/ingress/commit/6257e88af75faf0c8d6e1ca2d0c58f94c5f50afd) having been updated.

Would it make sense to [update `appVersion` and `tag`](https://github.com/caddyserver/ingress/commit/d162f5dc0287545b7d98c98924040eb13b3481d6) in charts automatically?

**Comment by mavimo** [comment]
@simenandre should be fixed with the update, I'm going to close this task, let's see how the next release goes :D
