### ISSUE TITLE
Crash on start up

### ISSUE THREAD

**Issue by BrettMayson** [caddyserver/ingress#23]
I am unable to get this running, I am using Helm 3.0.2 and Kubernetes 1.16.2

```
time="2020-01-30T17:05:30Z" level=warning msg="-namespace flag is unset, caddy ingress controller will monitor ingress resources in all namespaces."
W0130 17:05:30.720396       1 client_config.go:543] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
time="2020-01-30T17:05:30Z" level=info msg="Creating API client for https://10.245.0.1:443"
time="2020-01-30T17:05:30Z" level=info msg="Starting the caddy ingress controller"
time="2020-01-30T17:05:30Z" level=info msg="Exporting metrics on :9090"
2020/01/30 17:05:30.764	INFO	admin	admin endpoint started	{"address": "localhost:2019", "enforce_origin": false, "origins": ["localhost:2019"]}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xa0 pc=0x1576fce]

goroutine 29 [running]:
k8s.io/client-go/kubernetes.(*Clientset).CoreV1(...)
	/go/pkg/mod/k8s.io/client-go@v0.17.0/kubernetes/clientset.go:256
github.com/caddyserver/ingress/pkg/storage.(*SecretStorage).List(0xc0003975c0, 0x19c5274, 0x4, 0x1a88f00, 0x1, 0x10, 0x10, 0xc00039ebf0, 0x292ffc0)
	/app/pkg/storage/storage.go:116 +0x4e
github.com/mholt/certmagic.deleteOldOCSPStaples(0x1c73b80, 0xc0003975c0, 0x28, 0x28fb2d0)
	/go/pkg/mod/github.com/mholt/certmagic@v0.9.0/maintain.go:333 +0x63
github.com/mholt/certmagic.CleanStorage(0x1c73b80, 0xc0003975c0, 0x101, 0x44c1ff2520000)
	/go/pkg/mod/github.com/mholt/certmagic@v0.9.0/maintain.go:319 +0xdc
github.com/caddyserver/caddy/v2/modules/caddytls.(*TLS).cleanStorageUnits(0xc0003565a0)
	/go/pkg/mod/github.com/caddyserver/caddy/v2@v2.0.0-beta11/modules/caddytls/tls.go:296 +0x14d
github.com/caddyserver/caddy/v2/modules/caddytls.(*TLS).keepStorageClean(0xc0003565a0)
	/go/pkg/mod/github.com/caddyserver/caddy/v2@v2.0.0-beta11/modules/caddytls/tls.go:278 +0xaf
github.com/caddyserver/caddy/v2/modules/caddytls.(*TLS).Start(0xc0003565a0, 0x0, 0x0)
	/go/pkg/mod/github.com/caddyserver/caddy/v2@v2.0.0-beta11/modules/caddytls/tls.go:170 +0x132
github.com/caddyserver/caddy/v2.run.func4(0xc000303810, 0xc000307d00, 0xc00039bd40)
	/go/pkg/mod/github.com/caddyserver/caddy/v2@v2.0.0-beta11/caddy.go:384 +0xfa
github.com/caddyserver/caddy/v2.run(0xc000303810, 0x101, 0x0, 0x0)
	/go/pkg/mod/github.com/caddyserver/caddy/v2@v2.0.0-beta11/caddy.go:400 +0x2d2
github.com/caddyserver/caddy/v2.unsyncedDecodeAndRun(0xc00033ec60, 0x103, 0x120, 0xc00033ec60, 0x103)
	/go/pkg/mod/github.com/caddyserver/caddy/v2@v2.0.0-beta11/caddy.go:249 +0x97
github.com/caddyserver/caddy/v2.changeConfig(0x19c4d80, 0x4, 0x19c7bfc, 0x7, 0xc00033ea20, 0x103, 0x120, 0xc0002cb801, 0x0, 0x0)
	/go/pkg/mod/github.com/caddyserver/caddy/v2@v2.0.0-beta11/caddy.go:160 +0x508
github.com/caddyserver/caddy/v2.Load(...)
	/go/pkg/mod/github.com/caddyserver/caddy/v2@v2.0.0-beta11/caddy.go:99
github.com/caddyserver/ingress/internal/controller.(*CaddyController).reloadCaddy(0xc0002cc8f0, 0xc000056ef8, 0x5859d5)
	/app/internal/controller/controller.go:218 +0xa7
github.com/caddyserver/ingress/internal/controller.(*CaddyController).Run(0xc0002cc8f0, 0xc0000810e0)
	/app/internal/controller/controller.go:127 +0x43
created by main.main
	/app/cmd/caddy/main.go:62 +0x3b2
```

**Comment by eriklott** [comment]
I'm getting the same error as well.

**Comment by mholt** [comment]
Thanks for the report. Unfortunately, I don't currently have the time or funding to maintain this -- would really appreciate if the community would step up to help!

**Comment by oreoluwa** [comment]
@mholt, firstly, thank you for the awesome work done with Caddy, especially Caddy 2. While I'm currently evaluating how it might fit into my setup, I think I can see a great deal of benefits, especially with the OnDemand TLS(currently trying to setup a system that would require something like this). Secondly, thanks for putting in the time to make something for the Kubernetes fans out there. 
I was trying to experiment with this ingress as a replacement for nginx/gce ingress controllers and stumbled on this issue, as well.
While I'm not proficient with golang, I was able to figure out that this error was occurring because when the SecretStorage was instantiated, the KubeClient wasn't instantiated with or passed in to it.
I don't believe that setting it is suited for the `internal/caddy/config.go`, because the config options there looks like they could be marshaled to json and they look specific to caddyserver than the ingress (I can't make any assertions here, based on my limited knowledge of golang).
Temporarily, I added the `Provision` function, which I determined was being called after initializing, from reading the [modules.go](https://github.com/caddyserver/caddy/blob/v2/modules.go) code. The function instantiates a new kubeclient and sets the property on the SecretStorage instance.
I know this approach is probably not the best, given that now we have multiple instances of kubeclient being instantiated and if there are cluster specific configs, we'd need to keep duplicating that. Here's a [link to the PR](https://github.com/caddyserver/ingress/pull/24) https://github.com/caddyserver/ingress/pull/24 that shows my approach, along with some other changes I added for extensibility and image-building optimization.
PS: I'd welcome a better approach for injecting the KubeClient into the SecretStorage before the PR is mergeable; I made the PR primarily to save anyone interested in fixing this a long hour of debugging, plus some useful additions.
Please let me know your thoughts.

**Comment by mholt** [comment]
@oreoluwa That's excellent work! I'm glad your PR is at least something people can use in the meantime.

I do think some work is needed to restructure/redesign the ingress controller, but again, I don't know much about it myself. I'm happy to help discuss high-level design choices, and to give guidance relative to setting up / configuring Caddy, but on the K8s/ingress side, I'm not as qualified as you and others in the community are.

Can we find someone to work with you on it? I'd like to defer its development and leadership to the community for now. If we can find someone (or more than one), I'll send you all invites to our dev Slack.

**Comment by oreoluwa** [comment]
Thanks for the update @mholt.
I'm interested in the development of the Ingress, however I have a limited knowledge of golang(although, it's one of the things I intend to learn and do a lot more with this year).
However, do you have a roadmap or a project board or something that describes where the project is going?
I think these would probably provide some clarity and help with adherence to the design patterns for the project, as well as guiding the development process etc, for anyone interested in the project. As I imagine(from the stargazers), there a lot of people who are interested in this project and may know the ins/outs of k8s APIs, but may not easily know where their contributions may be needed or where to start from.

**Comment by mholt** [comment]
Yes, although, I don't have much of that to offer right now, either, sorry :)

Ideally, I'd like the ingress controller to be as self-contained as possible: i.e. a caddy module. Probably an [app module](https://caddyserver.com/docs/extending-caddy#apps)?

Basically, the controller should just configure Caddy to reverse proxy to the containers like it normally does. Caddy will take care of HTTPS for the various public hostnames. This would already make it way easier than other existing ingress controllers.

I can help give guidance as it pertains to Caddy configuration and modules, but not for Kubernetes-specific things. Others will need to help with that!

**Comment by mholt** [comment]
Here's an interesting discussion on HN about ingress controllers, performance, tradeoffs etc: https://news.ycombinator.com/item?id=21148370

**Comment by Embraser01** [comment]
Since this issue was created, the project has changed a lot, so I'm gonna close this issue. If this issue still happen on the latest version, feel free to open a new issue
