### ISSUE TITLE
Client IP behind loadbalancer

### ISSUE THREAD

**Issue by unixfox** [caddyserver/ingress#36]
Hello,

I just tested the latest helm chart: https://github.com/caddyserver/ingress/releases/tag/caddy-ingress-controller-0.0.1-rc1. It worked fine!

I was wondering if it would be possible to enable the proxy protocol support for Caddy? Currently, the requests appears to come from the load balancer IP address and that's not good for services that rely on knowing the IP address of the client.

Also, I tested if it worked out of the box and after enabling proxy protocol on Digitalocean kubernetes panel at each request I receive a 400 HTTP status code which means that caddy doesn't support the proxy protocol without configuring it.

**Comment by mavimo** [comment]
@unixfox thx to test it!

We have a PR WIP that will allow to configure all caddy global options via ConfigMap, see https://github.com/caddyserver/ingress/pull/30 to you think should be enough for your use case or you think that proxy protocol should be enabled by ingress?

In my opinion, since this will be enabled on the LoadBalancer I think that there is no reason to configure it on each single ingress but having it globally is the right solution, WDYT?

**Comment by unixfox** [comment]
I just discovered now that Caddy v2 doesn't support the proxy protocol yet: https://github.com/mastercactapus/caddy-proxyprotocol/issues/9

If caddy supported the proxy protocol, I would say it's better to have it globally enabled through a helm value like:
```yml
ingressController:
   proxyprotocol: true
```

**Comment by Embraser01** [comment]
Proxy protocol was added in #60 and can be enabled in the global config https://github.com/caddyserver/ingress/blob/78e7d5f68295a30f945a4e6e50abc5c33c220ac2/charts/caddy-ingress-controller/values.yaml#L32
