### ISSUE TITLE
Home Cluster ingress/IP address

### ISSUE THREAD

**Issue by olliephillips** [caddyserver/ingress#45]
This isn't an issue, I'm just trying to work out how I might use this ingress controller on a home Raspberry Pi K8s cluster. I have a couple of questions.

They are not urgent but a steer would be appreciated, I have googled extensively I promise.

1. Do I need Caddy installed as well, or is this effectively caddy-for-K8s and load balancing and reverse proxying is available out-the-box?

2. Do I need something like MetalLB on top of this in order to use my router IP address with the Caddy ingress controller? I'm confused here. When I try to get the IP I get "pending" presumably because by default it wants a cloud load balancer IP. I'm especially confused because this configuration puts a cloud load balancer in front of Caddy which itself can be a load balancer and reverse proxy?

3. If I don't need anything else, what is the process to use a local router IP with caddy ingress controller.  Is there a way to get it to use the external router IP.

Apologies, I don't have lots of experience with K8s so far.

**Comment by Embraser01** [comment]
Hi :wave:

> 1. Do I need Caddy installed as well, or is this effectively caddy-for-K8s and load balancing and reverse proxying is available out-the-box?

This project is a wrapper around Caddy, so you don't need to bring your own caddy instance.

> 2. Do I need something like MetalLB on top of this in order to use my router IP address with the Caddy ingress controller? I'm confused here. When I try to get the IP I get "pending" presumably because by default it wants a cloud load balancer IP. I'm especially confused because this configuration puts a cloud load balancer in front of Caddy which itself can be a load balancer and reverse proxy?

I'll answer the second question first as I'm not sure on the first anwser :smile:
Putting a Load Balancer in front of Caddy allows you to have a fix IP/DNS for your cluster inbound trafic. For example, if all your machines dies at the same time, all your DNS pointing to it wi

**Comment by Embraser01** [comment]
Hi :wave:

> 1. Do I need Caddy installed as well, or is this effectively caddy-for-K8s and load balancing and reverse proxying is available out-the-box?

This project is a wrapper around Caddy, so you don't need to bring your own caddy instance.

> 2. Do I need something like MetalLB on top of this in order to use my router IP address with the Caddy ingress controller? I'm confused here. When I try to get the IP I get "pending" presumably because by default it wants a cloud load balancer IP. I'm especially confused because this configuration puts a cloud load balancer in front of Caddy which itself can be a load balancer and reverse proxy?

I'll answer the second question first as I'm not sure on the first anwser :smile:
Putting a Load Balancer in front of Caddy allows you to have a fix IP/DNS for your cluster inbound trafic and also allows you to listen to public ports like 80 or 443. Public cloud providers prevent K8S Services to listen to ports less than 1024 (IIRC) for safety concerns, so the only way to listen to these ports is to use a Load Balancer that will be created by the cloud provider.

Client -> Load Balancer on :443 -> K8S Cluster on :5678 -> CaddyIngressController Service -> CaddyIngressController Pod


My guess would be that for a home config, you don't need to use a Load Balancer and just need the Service to listen to 80 and 443. I think you could also, depending on your router, just redirect the trafic from your router like this:

Client -> Router on :443 -> Raspberry Pi K8S Cluster on :5432 -> CaddyIngressController Service -> CaddyIngressController Pod

> 3. If I don't need anything else, what is the process to use a local router IP with caddy ingress controller. Is there a way to get it to use the external router IP.

If you create a Service in your cluster, it should be exposed on a random port and should be accessible through `<raspberry pi ip>:<random port>`. Then like I said, you can add a rule in your router to redirect traffic directly to this address.

Sorry if my answers aren't clear, I'm also quite new in the K8S world and it's been a couple of month since I worked on this

**Comment by olliephillips** [comment]
Hey @Embraser01. Thanks for taking the time to put all that together. I'll work through the suggestions and see if it helps.
Thanks again!
