### ISSUE TITLE
http => https redirects not working for root domain (@)

### ISSUE THREAD

**Issue by ThayalanGR** [caddyserver/ingress#50]
domain.com is assigned an certificate but when i hit http://domain.com or simply domain.com , caddy didn't automatically redirects to https

however the other scenario www.domain.com is cname pointed to domain.com is also assigned a cert and http => https redirects works fine.

and one more issue i'm facing is it shows something like this frequently (from pod's log)
![image](https://user-images.githubusercontent.com/35830033/96375379-61e38780-1196-11eb-81c2-e7f3ac17bab5.png)

**Comment by Embraser01** [comment]
Since this issue was created, the project has changed a lot, so I'm gonna close this issue. If this issue still happen on the latest version, feel free to open a new issue.

If I remember correctly, there was a small issue in caddy which made auto https redirects not working. It should be fixed now (and is working great for me)
