### ISSUE TITLE
Error: chart "caddy-ingress-controller" not found in https://caddyserver.github.io/ingress/ repository

### ISSUE THREAD

**Issue by crobin1** [caddyserver/ingress#73]
Hi,

I'm trying to deploy Caddy as an Ingress controller in my AKS cluster. When I try the provided commands, I get the following error:
`Error: chart "caddy-ingress-controller" not found in https://caddyserver.github.io/ingress/ repository`

I get the same error when adding the repo to my Helm repos first, and try to install the ingress controller then.

**Comment by VinGarcia** [comment]
Hello guys, I am also having this problem, is this happening to everyone or is it something in my environment?

**Comment by VinGarcia** [comment]
@crobin1 and maybe others that like me are not used to helm, apparently it is possible to build the helm package yourself, what I did was:

```bash
git clone https://github.com/caddyserver/ingress.git
cd ingress/charts/

# Then we create the .tgz package:
helm package caddy-ingress-controller/

# And we install it:
helm install mycaddyserver --namespace=caddy-system caddy-ingress-controller-0.0.1-rc3.tgz
```

I am not sure if I might be missing some important points here since I am very new to Helm, but it completed the installation process, I will try to see if everything is working now and I will report back if I find any problems.

I hope this is helpful.
