### ISSUE TITLE
Production ready?

### ISSUE THREAD

**Issue by stingalleman** [caddyserver/ingress#85]
Hi! I'm wondering if this ingress is production ready. It looks very nice! Seems like the latest release also isn't a pre-release.

**Comment by Embraser01** [comment]
Hi, the latest release is for the Helm Chart which needed to be bump to 1.0.0+ in order to be easily installable (without `--devel` opt.).

For the readiness for production of the controller, I'd tend to say yes even though there is a lot to be done.

Here is a quick list of pros and cons:

**Pros**
- I have been using it for more than a year with hundreds of ingresses without issues
- High Availability is available out of the box (also used for more than a year)
- Should soon have WAF capabilities (w/ https://github.com/corazawaf/coraza)

**Cons**
 - Not a lot of customization available yet for request manipulation (I'm working on a plugin system which will let anyone adapt their ingress config to caddy config)
 - No written tests (I hope to add some in the near futur🤞)
 - I'm currently the only one working on the project and have not a lot of time to do so (new contributors are welcome 👋)
 - ...probably more that I didn't see

**Comment by stingalleman** [comment]
Sounds great, but not having a lot of customisation options seems like a problem. I'll try it if I get the chance, thank you!
